project:
  type: website
  output-dir: docs

website:
  title: "Steven Mitchell"
  favicon: images/piko-logo.jpg
  navbar:
    title: false
    logo: images/piko-logo.jpg
    logo-alt: "The eyes of Piko, my black cat gazing out from a dark green background."
    left:
      - href: index.qmd
        text: About Me
      - href: work-samples.qmd
        text: Portfolio
      - href: photography.qmd
        text: Wildlife Photography
      - href: website-resume.pdf
        text: Resume
  page-footer:
    background: light
    left: Copyright 2024, Steven Mitchell
    right: This website and everything contained here was coded by me in R and hosted via GitHub. All photos found here are also my intellectual property.
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    
    toc: false
    page-layout: full

editor: visual

